apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #Data that helps uniquely identify the object
   name: postgres

spec: #What state you desire for the object
  selector:
    matchLabels:
      app: postgres 


  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: postgres
    spec:   #What state you desire for the object

      containers:
      - name:  postgres #container name
        image: postgres:13.3 #image name
        ports:
        - containerPort: 5432 # postgres runs on port 5432
        
        env:               
            - name: POSTGRES_USER
              value:  postgres
           
            - name: POSTGRES_PASSWORD
              value:  scooby
             
            - name: POSTGRES_DB
              value: training
